#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2025 IBM Corporation. All Rights Reserved.
#
# FS QA Test 1229
#
# fuzz fsx with atomic writes
#
. ./common/preamble
. ./common/atomicwrites
_begin_fstest rw auto quick atomicwrites

_require_odirect
_require_scratch_write_atomic

_scratch_mkfs >> $seqres.full 2>&1
_scratch_mount  >> $seqres.full 2>&1

testfile=$SCRATCH_MNT/testfile
touch $testfile

awu_max=$(_get_atomic_write_unit_max $testfile)
blksz=$(_get_block_size $SCRATCH_MNT)
bsize=`$here/src/min_dio_alignment $SCRATCH_MNT $SCRATCH_DEV`

# fsx usage:
#
# -N numops: total # operations to do
# -l flen: the upper bound on file size
# -o oplen: the upper bound on operation size (64k default)
# -Z: O_DIRECT ()

_run_fsx_on_file $testfile -N 10000 -o $awu_max -A -l 500000 -r $bsize -w $bsize -Z $FSX_AVOID  >> $seqres.full
if [[ "$?" != "0" ]]
then
	_fail "fsx returned error: $?"
fi

echo "Silence is golden"
status=0
exit
