#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2025 IBM Corporation. All Rights Reserved.
#
# FS QA Test 061
#
# Brute force all possible blocksize clustersize combination on a bigalloc
# filesystem for stressing atomic write using fio data crc verifier. We run
# nproc * 2 * $LOAD_FACTOR threads in parallel writing to a single
# $SCRATCH_MNT/test-file. With fio aio-dio atomic write this test ensures that
# we should never see the mix of data contents from different threads for any
# given fio blocksize.
#

. ./common/preamble
. ./common/atomicwrites

_begin_fstest auto rw stress atomicwrites

_require_scratch_write_atomic
_require_aiodio

FIO_LOAD=$(($(nproc) * 2 * LOAD_FACTOR))
SIZE=$((100*1024*1024))
fiobsize=4096

# Calculate fsblocksize as per bdev atomic write units.
bdev_awu_min=$(_get_atomic_write_unit_min $SCRATCH_DEV)
bdev_awu_max=$(_get_atomic_write_unit_max $SCRATCH_DEV)
fsblocksize=$(_max 4096 "$bdev_awu_min")

function create_fio_config()
{
cat >$fio_config <<EOF
	[aio-dio-aw-verify]
	direct=1
	ioengine=libaio
	rw=randwrite
	bs=$fiobsize
	fallocate=native
	filename=$SCRATCH_MNT/test-file
	size=$SIZE
	iodepth=$FIO_LOAD
	numjobs=$FIO_LOAD
	group_reporting=1
	verify_state_save=0
	verify=crc32c
	verify_fatal=1
	verify_dump=0
	verify_backlog=1024
	verify_async=4
	verify_write_sequence=0
	atomic=1
EOF
}

# Let's create a sample fio config to check whether fio supports all options.
fio_config=$tmp.fio
fio_out=$tmp.fio.out

create_fio_config
_require_fio $fio_config

for ((fsblocksize=$fsblocksize; fsblocksize <= $(_get_page_size); fsblocksize = $fsblocksize << 1)); do
	# cluster sizes above 16 x blocksize are experimental so avoid them
	# Also, cap cluster size at 128kb to keep it reasonable for large
	# blocks size
	fs_max_clustersize=$(_min $((16 * fsblocksize)) "$bdev_awu_max" $((128 * 1024)))

	for ((fsclustersize=$fsblocksize; fsclustersize <= $fs_max_clustersize; fsclustersize = $fsclustersize << 1)); do
		for ((fiobsize = $fsblocksize; fiobsize <= $fsclustersize; fiobsize = $fiobsize << 1)); do
			MKFS_OPTIONS="-O bigalloc -b $fsblocksize -C $fsclustersize"
			_scratch_mkfs_ext4  >> $seqres.full 2>&1 || continue
			if _try_scratch_mount >> $seqres.full 2>&1; then
				echo "== FIO test for fsblocksize=$fsblocksize fsclustersize=$fsclustersize fiobsize=$fiobsize ==" >> $seqres.full

				touch $SCRATCH_MNT/f1
				create_fio_config

				cat $fio_config >> $seqres.full

				$FIO_PROG $fio_config --output=$fio_out
				ret=$?
				cat $fio_out >> $seqres.full

				_scratch_unmount

				[[ $ret -eq 0 ]] || _fail "fio with atomic write failed"
			fi
		done
	done
done

# success, all done
echo Silence is golden
status=0
exit
